# Generated by Django 5.0.6 on 2024-07-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addactivity',
            name='level',
            field=models.IntegerField(choices=[(0, 'Level 1'), (1, 'Level 2'), (2, 'Level 3')], default=0),
            preserve_default=False,
        ),
    ]
