# Generated by Django 5.0.6 on 2024-07-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_addactivity_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addactivity',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='addactivity',
            name='level',
            field=models.IntegerField(choices=[(0, 'All levels'), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')]),
        ),
    ]
