# Generated by Django 5.0.6 on 2024-07-31 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='activity_id',
            new_name='activity_pk',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
