# Generated by Django 5.0.6 on 2024-08-12 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_addactivity_description_and_more'),
        ('reviews', '0002_rename_activity_id_review_activity_pk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='activity_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='activities.addactivity'),
        ),
    ]
